if(TARGET_PLATFORM STREQUAL "cm7")
    add_subdirectory(cm7)
elseif(TARGET_PLATFORM STREQUAL "cm4")
    add_subdirectory(cm4)
elseif(TARGET_PLATFORM STREQUAL "host")
    add_subdirectory(host)
# elseif(TARGET_PLATFORM STREQUAL "mcu_single_core_emu")
#     add_subdirectory(mcu_single_core_emu)
endif()
